# Generated by Django 3.0.8 on 2020-07-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desctiption',
            new_name='short_description',
        ),
    ]
