# Generated by Django 3.0.8 on 2020-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200723_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(),
        ),
    ]
