# Generated by Django 3.0.8 on 2020-07-23 05:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200723_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name=core.models.path_file_name),
        ),
    ]
